import type { ITranslation } from '@/hooks/useLanguage';

export const traducciones: ITranslation = {
    es: {
        badge: 'v2.0 Serverless Ready',
        title: 'La Plantilla Definitiva',
        titleHighlight: 'Full-Stack',
        description: 'Una base lista para producción para tu próxima gran idea. Construida con React 19, Node.js y Shadcn UI. Optimizada para Vercel y entornos Serverless.',
        getStarted: 'Empezar',
        viewComponents: 'Ver Componentes',
        everythingTitle: 'Todo lo que necesitas',
        everythingSubtitle: 'Conjunto completo de herramientas para el desarrollo web moderno.',
        featServerlessTitle: 'Serverless First',
        featServerlessDesc: 'Optimizado para funciones Vercel, eliminando cuellos de botella de arranque en frío y asegurando escalabilidad.',
        featStackTitle: 'Stack Moderno',
        featStackDesc: 'React 19, Vite, Tailwind v4 y Shadcn UI. La vanguardia de la tecnología frontend.',
        featAuthTitle: 'Autenticación Empresarial',
        featAuthDesc: 'Sistema seguro con JWT, control de acceso basado en roles y gestión de sesiones.',
        featDesignDesc: 'Arquitectura limpia separando responsabilidades. Fácil de extender y mantener mientras creces.',
        footerResources: 'Recursos',
        footerExplore: 'Explorar',
        footerDescr: 'La base sólida para tu próximo proyecto Full-Stack. Escalable, segura y lista para producción.',
        footerCatalog: 'Explorar Demo',
        footerShowcase: 'Galería de Componentes',
        footerCompany: 'Empresa',
        footerAbout: 'Nosotros',
        footerFaq: 'FAQ',
        footerContact: 'Contacto',
    },
    en: {
        badge: 'v2.0 Serverless Ready',
        title: 'The Ultimate',
        titleHighlight: 'Full-Stack Template',
        description: 'A production-ready foundation for your next big idea. Built with React 19, Node.js, and Shadcn UI. Optimized for Vercel and Serverless environments.',
        getStarted: 'Get Started',
        viewComponents: 'View Components',
        everythingTitle: 'Everything you need',
        everythingSubtitle: 'Comprehensive toolset for modern web development.',
        featServerlessTitle: 'Serverless First',
        featServerlessDesc: 'Optimized for Vercel functions, removing cold-start bottlenecks and ensuring scalability.',
        featStackTitle: 'Modern Stack',
        featStackDesc: 'React 19, Vite, Tailwind v4, and Shadcn UI. The bleeding edge of frontend tech.',
        featAuthTitle: 'Enterprise Auth',
        featAuthDesc: 'Secure authentication system with JWT, role-based access, and session management.',
        featDesignDesc: 'Clean architecture separating concerns. Easy to extend and maintain as you grow.',
        footerResources: 'Resources',
        footerExplore: 'Explore',
        footerDescr: 'The solid foundation for your next Full-Stack project. Scalable, secure, and production-ready.',
        footerCatalog: 'Explore Demo',
        footerShowcase: 'Component Gallery',
        footerCompany: 'Company',
        footerAbout: 'About Us',
        footerFaq: 'FAQ',
        footerContact: 'Contact',
    },
    pt: {
        badge: 'v2.0 Serverless Ready',
        title: 'O Template Final',
        titleHighlight: 'Full-Stack',
        description: 'Uma base pronta para produção para sua próxima grande ideia. Construída com React 19, Node.js e Shadcn UI. Otimizada para Vercel e ambientes Serverless.',
        getStarted: 'Começar',
        viewComponents: 'Ver Componentes',
        everythingTitle: 'Tudo o que você precisa',
        everythingSubtitle: 'Conjunto completo de ferramentas para o desenvolvimento web moderno.',
        featServerlessTitle: 'Serverless First',
        featServerlessDesc: 'Otimizado para funções Vercel, eliminando gargalos de inicialização a frio e garantindo escalabilidade.',
        featStackTitle: 'Stack Moderno',
        featStackDesc: 'React 19, Vite, Tailwind v4 e Shadcn UI. A vanguarda da tecnologia frontend.',
        featAuthTitle: 'Autenticação Empresarial',
        featAuthDesc: 'Sistema seguro com JWT, controle de acesso baseado em funções e gerenciamento de sessões.',
        featDesignTitle: 'Design Modular',
        featDesignDesc: 'Arquitetura limpa separando responsabilidades. Fácil de estender e manter conforme você cresce.',
        footerResources: 'Recursos',
        footerExplore: 'Explorar',
        footerDescr: 'A base sólida para o seu próximo projeto Full-Stack. Escalável, seguro e pronto para produção.',
        footerCatalog: 'Ver Demo',
        footerShowcase: 'Galeria de Componentes',
        footerCompany: 'Empresa',
        footerAbout: 'Sobre Nós',
        footerFaq: 'FAQ',
        footerContact: 'Contato',
    }
};
