export const traducciones = {
    es: {
        title: "Contacto y Soporte",
        subtitle: "Estamos aquí para ayudarte",
        formTitle: "Envíanos un mensaje",
        nameLabel: "Nombre completo",
        emailLabel: "Correo electrónico",
        typeLabel: "Tipo de consulta",
        subjectLabel: "Asunto",
        messageLabel: "Mensaje",
        typeSupport: "Soporte Técnico",
        typeFeedback: "Sugerencia / Feedback",
        typeBug: "Reporte de Error",
        submitButton: "Enviar Mensaje",
        sending: "Enviando...",
        successTitle: "Mensaje enviado",
        successMessage: "Hemos recibido tu mensaje correctamente. Te contactaremos pronto.",
        errorTitle: "Error",
        errorMessage: "Hubo un problema al enviar el mensaje. Inténtalo de nuevo.",
        legalNote: "Al enviar este formulario aceptas nuestra",
        privacyLink: "Política de Privacidad"
    },
    en: {
        title: "Contact & Support",
        subtitle: "We are here to help you",
        formTitle: "Send us a message",
        nameLabel: "Full Name",
        emailLabel: "Email Address",
        typeLabel: "Inquiry Type",
        subjectLabel: "Subject",
        messageLabel: "Message",
        typeSupport: "Technical Support",
        typeFeedback: "Suggestion / Feedback",
        typeBug: "Bug Report",
        submitButton: "Send Message",
        sending: "Sending...",
        successTitle: "Message Sent",
        successMessage: "We have received your message. We will contact you soon.",
        errorTitle: "Error",
        errorMessage: "There was a problem sending the message. Please try again.",
        legalNote: "By submitting this form you agree to our",
        privacyLink: "Privacy Policy"
    },
    pt: {
        title: "Contato e Suporte",
        subtitle: "Estamos aqui para ajudar",
        formTitle: "Envie-nos uma mensagem",
        nameLabel: "Nome completo",
        emailLabel: "Endereço de e-mail",
        typeLabel: "Tipo de consulta",
        subjectLabel: "Assunto",
        messageLabel: "Mensagem",
        typeSupport: "Suporte Técnico",
        typeFeedback: "Sugestão / Feedback",
        typeBug: "Relatório de Erro",
        submitButton: "Enviar Mensagem",
        sending: "Enviando...",
        successTitle: "Mensagem Enviada",
        successMessage: "Recebemos sua mensagem. Entraremos em contato em breve.",
        errorTitle: "Erro",
        errorMessage: "Houve um problema ao enviar a mensagem. Tente novamente.",
        legalNote: "Ao enviar este formulário você aceita nossa",
        privacyLink: "Política de Privacidade"
    }
};
