import type { Language } from '@/contexts/LanguageContext/context';

export const traducciones: { [key in Language]: Record<string, string> } = {
    es: {
        title: 'Iniciar Sesión',
        subtitle: '¿No tienes cuenta?',
        signupLink: 'Regístrate aquí',
        emailLabel: 'Correo electrónico',
        emailPlaceholder: 'tu@email.com',
        passwordLabel: 'Contraseña',
        passwordPlaceholder: '••••••••',
        rememberMe: 'Recordarme',
        forgotPassword: '¿Olvidaste tu contraseña?',
        loginButton: 'Iniciar Sesión',
        loggingIn: 'Iniciando sesión...',
        orContinueWith: 'O continúa con',
        googleButton: 'Continuar con Google',
        googleSuccess: '¡Bienvenido! Has iniciado sesión con Google',
        googleError: 'Error al iniciar sesión con Google',
    },
    en: {
        title: 'Sign In',
        subtitle: "Don't have an account?",
        signupLink: 'Sign up here',
        emailLabel: 'Email',
        emailPlaceholder: 'you@email.com',
        passwordLabel: 'Password',
        passwordPlaceholder: '••••••••',
        rememberMe: 'Remember me',
        forgotPassword: 'Forgot your password?',
        loginButton: 'Sign In',
        loggingIn: 'Signing in...',
        orContinueWith: 'Or continue with',
        googleButton: 'Continue with Google',
        googleSuccess: 'Welcome! You signed in with Google',
        googleError: 'Error signing in with Google',
    },
    pt: {
        title: 'Entrar',
        subtitle: 'Não tem uma conta?',
        signupLink: 'Cadastre-se aqui',
        emailLabel: 'E-mail',
        emailPlaceholder: 'seu@email.com',
        passwordLabel: 'Senha',
        passwordPlaceholder: '••••••••',
        rememberMe: 'Lembrar-me',
        forgotPassword: 'Esqueceu sua senha?',
        loginButton: 'Entrar',
        loggingIn: 'Entrando...',
        orContinueWith: 'Ou continue com',
        googleButton: 'Continuar com Google',
        googleSuccess: 'Bem-vindo! Você entrou com Google',
        googleError: 'Erro ao entrar com Google',
    },
};
