import type { ITranslation } from '@/hooks/useLanguage';
import { BRANDING } from '@/config/branding';

export const traduccionesSidebar: ITranslation = {
    es: {
        home: 'Inicio',
        search: 'Comparador',
        stats: 'Estadísticas',
        vault: 'Bóveda',
        profile: 'Perfil',
        notifications: 'Notificaciones',
        settings: 'Ajustes',
        appTitle: 'Caminando',
        copyright: `© ${new Date().getFullYear()} ${BRANDING.appName}`,
        welcomeAdminPanel: 'Bienvenido al Panel de Administración',
        pageNotFound: 'Página no encontrada',
        privacy: 'Privacidad',
        terms: 'Términos',
        github: 'GitHub',
        portfolio: 'Portfolio',
        // Dashboard sidebar
        dashboard: 'Dashboard',
        users: 'Usuarios',
        tickets: 'Soporte',
        ecommerce: 'E-commerce',
        products: 'Productos',
        categories: 'Categorías',
        brands: 'Marcas',
        attributes: 'Atributos',
        database: 'Base de Datos',
        security: 'Seguridad',
        images: 'Imágenes',
        campaigns: 'Campañas',
        system: 'Configuración',
        logout: 'Cerrar Sesión',
        language: 'Idioma',
        theme: 'Tema',
        mongodb: 'MongoDB',
        redis: 'Redis',
        emails: 'Correos',
        scraper: 'Scraper',
    },
    en: {
        home: 'Home',
        search: 'Comparator',
        stats: 'Statistics',
        vault: 'Vault',
        profile: 'Profile',
        notifications: 'Notifications',
        settings: 'Settings',
        appTitle: 'Caminando',
        copyright: `© ${new Date().getFullYear()} ${BRANDING.appName}`,
        welcomeAdminPanel: 'Welcome to the Admin Panel',
        pageNotFound: 'Page not found',
        privacy: 'Privacy',
        terms: 'Terms',
        github: 'GitHub',
        portfolio: 'Portfolio',
        // Dashboard sidebar
        dashboard: 'Dashboard',
        users: 'Users',
        tickets: 'Support',
        ecommerce: 'E-commerce',
        products: 'Products',
        categories: 'Categories',
        brands: 'Brands',
        attributes: 'Attributes',
        database: 'Database',
        security: 'Security',
        images: 'Images',
        campaigns: 'Campaigns',
        system: 'Settings',
        logout: 'Logout',
        language: 'Language',
        theme: 'Theme',
        mongodb: 'MongoDB',
        redis: 'Redis',
        emails: 'Emails',
        scraper: 'Scraper',
    },
    pt: {
        home: 'Início',
        search: 'Comparador',
        stats: 'Estatísticas',
        vault: 'Cofre',
        profile: 'Perfil',
        notifications: 'Notificações',
        settings: 'Configurações',
        appTitle: 'Caminando',
        copyright: `© ${new Date().getFullYear()} ${BRANDING.appName}`,
        welcomeAdminPanel: 'Bem-vindo ao Painel de Administração',
        pageNotFound: 'Página não encontrada',
        privacy: 'Privacidade',
        terms: 'Termos',
        github: 'GitHub',
        portfolio: 'Portfólio',
        // Dashboard sidebar
        dashboard: 'Dashboard',
        users: 'Usuários',
        tickets: 'Suporte',
        ecommerce: 'E-commerce',
        products: 'Produtos',
        categories: 'Categorias',
        brands: 'Marcas',
        attributes: 'Atributos',
        database: 'Banco de Dados',
        security: 'Segurança',
        images: 'Imagens',
        campaigns: 'Campanhas',
        system: 'Configuração',
        logout: 'Sair',
        language: 'Idioma',
        theme: 'Tema',
        mongodb: 'MongoDB',
        redis: 'Redis',
        emails: 'E-mails',
        scraper: 'Scraper',
    }
};
