import type { Language } from '@/contexts/LanguageContext/context';

export const traducciones: { [key in Language]: Record<string, string> } = {
    es: {
        title: 'Crear Cuenta',
        subtitle: '¿Ya tienes cuenta?',
        loginLink: 'Inicia sesión aquí',
        nameLabel: 'Nombre completo',
        namePlaceholder: 'Juan Pérez',
        emailLabel: 'Correo electrónico',
        emailPlaceholder: 'tu@email.com',
        passwordLabel: 'Contraseña',
        passwordPlaceholder: '••••••••',
        passwordHint: 'Mínimo 8 caracteres, 1 mayúscula y 1 número',
        termsLabel: 'Acepto los',
        termsLink: 'términos y condiciones',
        and: 'y la',
        privacyLink: 'política de privacidad',
        registerButton: 'Crear Cuenta',
        registering: 'Creando cuenta...',
        orContinueWith: 'O continúa con',
        googleButton: 'Continuar con Google',
        googleSuccess: '¡Bienvenido! Cuenta creada con Google',
        googleError: 'Error al registrarse con Google',
    },
    en: {
        title: 'Create Account',
        subtitle: 'Already have an account?',
        loginLink: 'Sign in here',
        nameLabel: 'Full name',
        namePlaceholder: 'John Doe',
        emailLabel: 'Email',
        emailPlaceholder: 'you@email.com',
        passwordLabel: 'Password',
        passwordPlaceholder: '••••••••',
        passwordHint: 'Minimum 8 characters, 1 uppercase and 1 number',
        termsLabel: 'I accept the',
        termsLink: 'terms and conditions',
        and: 'and the',
        privacyLink: 'privacy policy',
        registerButton: 'Create Account',
        registering: 'Creating account...',
        orContinueWith: 'Or continue with',
        googleButton: 'Continue with Google',
        googleSuccess: 'Welcome! Account created with Google',
        googleError: 'Error registering with Google',
    },
    pt: {
        title: 'Criar Conta',
        subtitle: 'Já tem uma conta?',
        loginLink: 'Entre aqui',
        nameLabel: 'Nome completo',
        namePlaceholder: 'João Silva',
        emailLabel: 'E-mail',
        emailPlaceholder: 'seu@email.com',
        passwordLabel: 'Senha',
        passwordPlaceholder: '••••••••',
        passwordHint: 'Mínimo 8 caracteres, 1 maiúscula e 1 número',
        termsLabel: 'Aceito os',
        termsLink: 'termos e condições',
        and: 'e a',
        privacyLink: 'política de privacidade',
        registerButton: 'Criar Conta',
        registering: 'Criando conta...',
        orContinueWith: 'Ou continue com',
        googleButton: 'Continuar com Google',
        googleSuccess: 'Bem-vindo! Conta criada com Google',
        googleError: 'Erro ao registrar-se com Google',
    },
};
