import type { ITranslation } from '@/hooks/useLanguage';

export const traducciones: ITranslation = {
    es: {
        title: 'Productos',
        description: 'Explora nuestro catálogo completo de productos',
        comingSoon: 'Próximamente',
        comingSoonDesc: 'Estamos trabajando en el catálogo de productos. Vuelve pronto para ver todas nuestras ofertas.',
        home: 'Inicio',
        allProducts: 'Todos los productos',
        back: 'Volver',

        // Product Card & Catalog
        featured: 'Destacado',
        outOfStock: 'Sin Stock',
        details: 'Ver más',
        addShort: 'Añadir',
        addToCart: 'Añadir al carrito',
        lowStock: '¡Últimas unidades!',

        // Filters Sidebar
        filters: 'Filtros',
        categories: 'Categorías',
        brands: 'Marcas',
        priceRange: 'Rango de Precio',
        attributes: 'Atributos',
        clearFilters: 'Limpiar Filtros',
        apply: 'Aplicar',

        // Pagination & State
        showing: 'Mostrando {{count}} de {{total}} productos',
        noResults: 'No se encontraron productos con estos filtros',
        loading: 'Cargando catálogo...',
        loadMore: 'Cargar más',
        sort: 'Ordenar por',
        sortNewest: 'Novedades',
        sortPriceAsc: 'Menor Precio',
        sortPriceDesc: 'Mayor Precio',
        sortName: 'Nombre',
    },
    en: {
        title: 'Products',
        description: 'Explore our complete product catalog',
        comingSoon: 'Coming Soon',
        comingSoonDesc: 'We are working on the product catalog. Check back soon to see all our offerings.',
        home: 'Home',
        allProducts: 'All products',
        back: 'Back',

        featured: 'Featured',
        outOfStock: 'Out of Stock',
        details: 'View details',
        addShort: 'Add',
        addToCart: 'Add to cart',
        lowStock: 'Last units!',

        filters: 'Filters',
        categories: 'Categories',
        brands: 'Brands',
        priceRange: 'Price Range',
        attributes: 'Attributes',
        clearFilters: 'Clear Filters',
        apply: 'Apply',

        showing: 'Showing {{count}} of {{total}} products',
        noResults: 'No products found with these filters',
        loading: 'Loading catalog...',
        loadMore: 'Load more',
        sort: 'Sort by',
        sortNewest: 'Newest',
        sortPriceAsc: 'Price: Low to High',
        sortPriceDesc: 'Price: High to Low',
        sortName: 'Name',
    },
    pt: {
        title: 'Produtos',
        description: 'Explore nosso catálogo completo de produtos',
        comingSoon: 'Em Breve',
        comingSoonDesc: 'Estamos trabalhando no catálogo de produtos. Volte em breve para ver todas as nossas ofertas.',
        home: 'Início',
        allProducts: 'Todos os produtos',
        back: 'Voltar',

        featured: 'Destaque',
        outOfStock: 'Sem Estoque',
        details: 'Ver mais',
        addShort: 'Adicionar',
        addToCart: 'Adicionar ao carrinho',
        lowStock: 'Últimas unidades!',

        filters: 'Filtros',
        categories: 'Categorias',
        brands: 'Marcas',
        priceRange: 'Faixa de Preço',
        attributes: 'Atributos',
        clearFilters: 'Limpar Filtros',
        apply: 'Aplicar',

        showing: 'Mostrando {{count}} de {{total}} produtos',
        noResults: 'Nenhum produto encontrado com estes filtros',
        loading: 'Carregando catálogo...',
        loadMore: 'Carregar mais',
        sort: 'Ordenar por',
        sortNewest: 'Novidades',
        sortPriceAsc: 'Menor Preço',
        sortPriceDesc: 'Mayor Preço',
        sortName: 'Nome',
    },
};
