import type { ITranslation } from '../../../../hooks/useLanguage';

export const traducciones: ITranslation = {
    es: {
        title: 'Ajustes',
        subtitle: 'Configura tu perfil y preferencias',
        profile: 'Perfil',
        name: 'Nombre',
        email: 'Correo electrónico',
        bio: 'Biografía',
        bioPlaceholder: 'Cuéntanos sobre ti...',
        avatar: 'Avatar',
        changeAvatar: 'Cambiar avatar',
        uploadNew: 'Subir nueva imagen',
        saveChanges: 'Guardar cambios',
        preferences: 'Preferencias',
        currency: 'Moneda',
        language: 'Idioma',
        notifications: 'Notificaciones',
        recurringReminders: 'Recordatorios recurrentes',
        recurringRemindersDesc: 'Recordatorios para compras habituales',
        newsletter: 'Newsletter',
        newsletterDesc: 'Recibir noticias y ofertas especiales',
        syncCompleted: 'Sincronización completada',
        syncCompletedDesc: 'Notificar cuando se complete la sincronización',
        changesSaved: 'Cambios guardados exitosamente',
    },
    en: {
        title: 'Settings',
        subtitle: 'Configure your profile and preferences',
        profile: 'Profile',
        name: 'Name',
        email: 'Email',
        bio: 'Bio',
        bioPlaceholder: 'Tell us about yourself...',
        avatar: 'Avatar',
        changeAvatar: 'Change avatar',
        uploadNew: 'Upload new image',
        saveChanges: 'Save changes',
        preferences: 'Preferences',
        currency: 'Currency',
        language: 'Language',
        notifications: 'Notifications',
        recurringReminders: 'Recurring reminders',
        recurringRemindersDesc: 'Reminders for regular purchases',
        newsletter: 'Newsletter',
        newsletterDesc: 'Receive news and special offers',
        syncCompleted: 'Sync completed',
        syncCompletedDesc: 'Notify when synchronization is complete',
        changesSaved: 'Changes saved successfully',
    },
    pt: {
        title: 'Configurações',
        subtitle: 'Configure seu perfil e preferências',
        profile: 'Perfil',
        name: 'Nome',
        email: 'Email',
        bio: 'Biografia',
        bioPlaceholder: 'Conte-nos sobre você...',
        avatar: 'Avatar',
        changeAvatar: 'Alterar avatar',
        uploadNew: 'Enviar nova imagem',
        saveChanges: 'Salvar alterações',
        preferences: 'Preferências',
        currency: 'Moeda',
        language: 'Idioma',
        notifications: 'Notificações',
        recurringReminders: 'Lembretes recorrentes',
        recurringRemindersDesc: 'Lembretes para compras habituais',
        newsletter: 'Newsletter',
        newsletterDesc: 'Receber notícias e ofertas especiais',
        syncCompleted: 'Sincronização concluída',
        syncCompletedDesc: 'Notificar quando a sincronização for concluída',
        changesSaved: 'Alterações salvas com sucesso',
    },
};
