import type { ITranslation } from '@/hooks/useLanguage';

export const traduccionAdminUsers: ITranslation = {
    es: {
        title: 'Usuarios',
        subtitle: 'Gestión de usuarios registrados y administradores.',
        searchPlaceholder: 'Buscar por email, nombre...',
        tableUser: 'Usuario',
        tableRole: 'Rol',
        tableStatus: 'Estado',
        tableRegistered: 'Registro',
        tableStats: 'Estadísticas',
        tableActions: 'Acciones',
        viewDetails: 'Ver detalles',
        roleAdmin: 'Admin',
        roleUser: 'Usuario',
        statusActive: 'Activo',
        statusInactive: 'Inactivo',
        carts: 'Carritos',
        alerts: 'Alertas',
        actionDeactivate: 'Desactivar usuario',
        actionActivate: 'Activar usuario',
        previous: 'Anterior',
        next: 'Siguiente',
        pageInfo: 'Página {{page}} de {{total}}',
        loading: 'Cargando usuarios...',
        noUsers: 'No se encontraron usuarios',
        successUpdate: 'Estado del usuario actualizado',
        errorUpdate: 'Error al actualizar estado',
        // User Detail
        userNotFound: 'Usuario no encontrado',
        personalInfo: 'Información Personal',
        registered: 'Registrado',
        clientId: 'ID Cliente',
        usageStats: 'Estadísticas de Uso',
        historyTitle: 'Historial de Seguridad y Accesos',
    },
    en: {
        title: 'Users',
        subtitle: 'Management of registered users and administrators.',
        searchPlaceholder: 'Search by email, name...',
        tableUser: 'User',
        tableRole: 'Role',
        tableStatus: 'Status',
        tableRegistered: 'Registered',
        tableStats: 'Stats',
        tableActions: 'Actions',
        viewDetails: 'View details',
        roleAdmin: 'Admin',
        roleUser: 'User',
        statusActive: 'Active',
        statusInactive: 'Inactive',
        carts: 'Carts',
        alerts: 'Alerts',
        actionDeactivate: 'Deactivate user',
        actionActivate: 'Activate user',
        previous: 'Previous',
        next: 'Next',
        pageInfo: 'Page {{page}} of {{total}}',
        loading: 'Loading users...',
        noUsers: 'No users found',
        successUpdate: 'User status updated',
        errorUpdate: 'Error updating status',
        // User Detail
        userNotFound: 'User not found',
        personalInfo: 'Personal Information',
        registered: 'Registered',
        clientId: 'Client ID',
        usageStats: 'Usage Statistics',
        historyTitle: 'Security and Access History',
    },
    pt: {
        title: 'Usuários',
        subtitle: 'Gestão de usuários registrados e administradores.',
        searchPlaceholder: 'Buscar por email, nome...',
        tableUser: 'Usuário',
        tableRole: 'Função',
        tableStatus: 'Estado',
        tableRegistered: 'Registro',
        tableStats: 'Estatísticas',
        tableActions: 'Ações',
        viewDetails: 'Ver detalhes',
        roleAdmin: 'Admin',
        roleUser: 'Usuário',
        statusActive: 'Ativo',
        statusInactive: 'Inativo',
        carts: 'Carrinhos',
        alerts: 'Alertas',
        actionDeactivate: 'Desativar usuário',
        actionActivate: 'Ativar usuário',
        previous: 'Anterior',
        next: 'Próximo',
        pageInfo: 'Página {{page}} de {{total}}',
        loading: 'Carregando usuários...',
        noUsers: 'Nenhum usuário encontrado',
        successUpdate: 'Status do usuário atualizado',
        errorUpdate: 'Erro ao atualizar status',
        // User Detail
        userNotFound: 'Usuário não encontrado',
        personalInfo: 'Informações Pessoais',
        registered: 'Registrado',
        clientId: 'ID Cliente',
        usageStats: 'Estatísticas de Uso',
        historyTitle: 'Histórico de Segurança e Acessos',
    }
};
