import type { ITranslation } from '@/hooks/useLanguage';

export const traduccionesHeader: ITranslation = {
    es: {
        home: 'Inicio',
        products: 'Productos',
        features: 'Características',
        about: 'Nosotros',
        faq: 'FAQ',
        dashboard: 'Dashboard',
        profile: 'Mi Perfil',
        settings: 'Configuración',
        logout: 'Cerrar Sesión',
        login: 'Iniciar Sesión',
        menuTitle: 'Menú',
        navigation: 'Navegación',
        preferences: 'Preferencias',
        theme: 'Tema',
        language: 'Idioma',
        notifications: 'Notificaciones',
        guestUser: 'Usuario',
        themeLight: 'Claro',
        themeDark: 'Oscuro',
        themeBlue: 'Azul',
        themeRed: 'Rojo',
        themeGreen: 'Verde',
        contact: 'Contacto'
    },
    en: {
        home: 'Home',
        products: 'Products',
        features: 'Features',
        about: 'About Us',
        faq: 'FAQ',
        dashboard: 'Dashboard',
        profile: 'My Profile',
        settings: 'Settings',
        logout: 'Log Out',
        login: 'Log In',
        menuTitle: 'Menu',
        navigation: 'Navigation',
        preferences: 'Preferences',
        theme: 'Theme',
        language: 'Language',
        notifications: 'Notifications',
        guestUser: 'User',
        themeLight: 'Light',
        themeDark: 'Dark',
        themeBlue: 'Blue',
        themeRed: 'Red',
        themeGreen: 'Green',
        contact: 'Contact'
    },
    pt: {
        home: 'Início',
        products: 'Produtos',
        features: 'Recursos',
        about: 'Sobre Nós',
        faq: 'FAQ',
        dashboard: 'Dashboard',
        profile: 'Meu Perfil',
        settings: 'Configurações',
        logout: 'Sair',
        login: 'Entrar',
        menuTitle: 'Menu',
        navigation: 'Navegação',
        preferences: 'Preferências',
        theme: 'Tema',
        language: 'Idioma',
        notifications: 'Notificações',
        guestUser: 'Usuário',
        themeLight: 'Claro',
        themeDark: 'Escuro',
        themeBlue: 'Azul',
        themeRed: 'Vermelho',
        themeGreen: 'Verde',
        contact: 'Contato'
    }
};
