import type { ITranslation } from '@/hooks/useLanguage';

export const traducciones: ITranslation = {
    es: {
        hello: 'Hola',
        user: 'Usuario',
        welcome: 'Bienvenido a tu panel de control.',
        settings: 'Ajustes',
        accountStatus: 'Estado de Cuenta',
        active: 'Activo',
        planStandard: 'Plan Estándar',
        security: 'Seguridad',
        protected: 'Protegido',
        authEnabled: '2FA Habilitado hoy',
        recentActivity: 'Actividad Reciente',
        vsLastMonth: 'vs. mes pasado',
        generalSummary: 'Resumen General',
        activityChart: 'Gráfico de actividad (Placeholder)',
        recentAccess: 'Accesos Recientes',
        loginHistory: 'Tu historial de inicio de sesión',
        new: 'Nuevo',
        loginFrom: 'Inicio de sesión desde',
        profileUpdated: 'Perfil actualizado recientemente'
    },
    en: {
        hello: 'Hello',
        user: 'User',
        welcome: 'Welcome to your control panel.',
        settings: 'Settings',
        accountStatus: 'Account Status',
        active: 'Active',
        planStandard: 'Standard Plan',
        security: 'Security',
        protected: 'Protected',
        authEnabled: '2FA Enabled today',
        recentActivity: 'Recent Activity',
        vsLastMonth: 'vs. last month',
        generalSummary: 'General Summary',
        activityChart: 'Activity Chart (Placeholder)',
        recentAccess: 'Recent Access',
        loginHistory: 'Your login history',
        new: 'New',
        loginFrom: 'Login from',
        profileUpdated: 'Profile updated recently'
    },
    pt: {
        hello: 'Olá',
        user: 'Usuário',
        welcome: 'Bem-vindo ao seu painel de controle.',
        settings: 'Configurações',
        accountStatus: 'Estado da Conta',
        active: 'Ativo',
        planStandard: 'Plano Padrão',
        security: 'Segurança',
        protected: 'Protegido',
        authEnabled: '2FA Ativado hoje',
        recentActivity: 'Atividade Recente',
        vsLastMonth: 'vs. mês passado',
        generalSummary: 'Resumo Geral',
        activityChart: 'Gráfico de atividade (Placeholder)',
        recentAccess: 'Acessos Recentes',
        loginHistory: 'Seu histórico de login',
        new: 'Novo',
        loginFrom: 'Login de',
        profileUpdated: 'Perfil atualizado recentemente'
    }
};
