import type { ITranslation } from '../../hooks/useLanguage';

export const traducciones: ITranslation = {
    es: {
        title: 'Sesiones activas',
        subtitle: 'Gestiona los dispositivos donde has iniciado sesión',
        refresh: 'Actualizar',
        closeOthers: 'Cerrar otras',
        closing: 'Cerrando...',
        currentSession: 'Sesión actual',
        lastActivity: 'Última actividad',
        startedAt: 'Iniciada',
        noSessions: 'No hay sesiones activas',
        loading: 'Cargando sesiones...',
        terminateSuccess: 'Sesión cerrada exitosamente',
        terminateError: 'Error al cerrar sesión',
        terminateAllSuccess: 'Todas las demás sesiones fueron cerradas',
        terminateAllError: 'Error al cerrar sesiones',
        loadError: 'Error al cargar sesiones',
        now: 'Ahora',
        minutesAgo: 'Hace {{value}}m',
        hoursAgo: 'Hace {{value}}h',
        daysAgo: 'Hace {{value}}d',
    },
    en: {
        title: 'Active sessions',
        subtitle: 'Manage the devices where you are signed in',
        refresh: 'Refresh',
        closeOthers: 'Sign out others',
        closing: 'Signing out...',
        currentSession: 'Current session',
        lastActivity: 'Last activity',
        startedAt: 'Started',
        noSessions: 'No active sessions',
        loading: 'Loading sessions...',
        terminateSuccess: 'Session closed successfully',
        terminateError: 'Error closing session',
        terminateAllSuccess: 'All other sessions were closed',
        terminateAllError: 'Error closing sessions',
        loadError: 'Error loading sessions',
        now: 'Just now',
        minutesAgo: '{{value}}m ago',
        hoursAgo: '{{value}}h ago',
        daysAgo: '{{value}}d ago',
    },
    pt: {
        title: 'Sessões ativas',
        subtitle: 'Gerencie os dispositivos onde você está conectado',
        refresh: 'Atualizar',
        closeOthers: 'Encerrar outras',
        closing: 'Encerrando...',
        currentSession: 'Sessão atual',
        lastActivity: 'Última atividade',
        startedAt: 'Iniciada',
        noSessions: 'Nenhuma sessão ativa',
        loading: 'Carregando sessões...',
        terminateSuccess: 'Sessão encerrada com sucesso',
        terminateError: 'Erro ao encerrar sessão',
        terminateAllSuccess: 'Todas as outras sessões foram encerradas',
        terminateAllError: 'Erro ao encerrar sessões',
        loadError: 'Erro ao carregar sessões',
        now: 'Agora',
        minutesAgo: 'Há {{value}}m',
        hoursAgo: 'Há {{value}}h',
        daysAgo: 'Há {{value}}d',
    },
};
