import type { ITranslation } from '@/hooks/useLanguage';
import { BRANDING } from '@/config/branding';

export const traducciones: ITranslation = {
    es: {
        legalNotice: 'Aviso Legal',
        privacyPolicy: 'Política de Privacidad',
        cookiesPolicy: 'Política de Cookies',
        termsConditions: 'Términos y Condiciones',
        salesConditions: 'Condiciones de Contratación',

        legalNoticeSubtitle: 'Identificación y datos de contacto',
        objectTitle: 'Objeto',
        objectDesc: 'Este sitio web tiene como objeto proporcionar una plataforma digital para la gestión y visualización de contenidos y servicios corporativos, permitiendo al usuario interactuar directamente con la plataforma.',

        // Datos del Titular (Placeholders)
        ownerTitle: 'Información del Titular',
        ownerName: `${BRANDING.appName} S.L.`,
        ownerFiscalId: 'NIF: B-12345678',
        ownerAddress: 'Dirección: Av. Principal 123, Madrid, España',
        ownerEmail: `Contacto: info@${BRANDING.appName.toLowerCase().replace(/\s+/g, '')}.com`,

        // Secciones Privacidad
        dataCollection: 'Recogida de Datos',
        dataCollectionDesc: 'Recogemos datos personales necesarios para la prestación de servicios, gestión de usuarios y facturación, así como datos de navegación para mejorar la experiencia.',
        dataPurpose: 'Finalidad del Tratamiento',
        dataPurposeDesc: 'Los datos se utilizan exclusivamente para procesar tus solicitudes, gestionar accesos, atender incidencias y mejorar nuestros servicios.',
        userRights: 'Derechos del Usuario',
        userRightsDesc: `Puedes ejercer tus derechos de acceso, rectificación, supresión y portabilidad a través del sistema de soporte integrado en la plataforma o escribiendo a info@${BRANDING.appName.toLowerCase().replace(/\s+/g, '')}.com.`,
        privacySubtitle: 'Cómo protegemos tus datos personales',

        // Secciones Cookies
        cookieIntro: 'Utilizamos cookies técnicas necesarias para el funcionamiento y analíticas para entender cómo se usa el sitio.',
        essentialCookies: 'Cookies Esenciales',
        analyticalCookies: 'Cookies Analíticas',
        essentialCookiesDesc: 'Nombre: `theme-preference`, `language-preference`, `auth-data`. Finalidad: Mantener tus preferencias de navegación y sesión segura.',
        analyticalCookiesDesc: 'Utilizamos herramientas de análisis para entender patrones de uso y mejorar nuestra plataforma, sin identificar usuarios individualmente.',
        cookieBannerText: 'Utilizamos cookies para garantizar la mejor experiencia. Al continuar, aceptas nuestra política.',
        accept: 'Aceptar',
        decline: 'Rechazar',
        moreInfo: 'Más información',
        cookiesSubtitle: 'Uso de cookies y tecnologías similares',

        // Secciones Términos
        usageRules: 'Reglas de Uso',
        usageRulesDesc: 'El usuario se compromete a utilizar la plataforma únicamente para realizar consultas y acciones legítimas, evitando cualquier actividad fraudulenta.',
        liability: 'Limitación de Responsabilidad',
        liabilityDesc: `${BRANDING.appName} se esfuerza por mostrar información precisa, pero nos reservamos el derecho a corregir errores en precios o descripciones. No nos hacemos responsables de interrupciones técnicas ajenas a nuestro control.`,
        intellectualPropertyTitle: 'Propiedad Intelectual',
        intellectualPropertyDesc: `Todo el contenido (imágenes, textos, software) es propiedad exclusiva de ${BRANDING.appName} S.L. o sus licenciantes. Queda prohibida su reproducción sin autorización.`,
        termsSubtitle: 'Condiciones generales de uso del servicio',

        // Secciones Condiciones de Contratación
        salesSubtitle: 'Condiciones de compra y devoluciones',
        pricesTitle: '1. Precios e Impuestos',
        pricesDesc: 'Todos los precios incluyen el IVA vigente. Los gastos de envío se calculan en el checkout antes de finalizar la compra.',
        paymentTitle: '2. Métodos de Pago',
        paymentDesc: 'Aceptamos pagos seguros mediante tarjeta de crédito/débito y otros métodos indicados en el proceso de compra.',
        withdrawalTitle: '3. Devoluciones y Desistimiento',
        withdrawalDesc: 'Dispones de 14 días naturales para devolver tu pedido si no estás satisfecho, siempre que los productos estén en su estado original.',
        warrantyTitle: '4. Garantía',
        warrantyDesc: `Todos nuestros servicios cuentan con la garantía de calidad de la plataforma. Para soporte, contacta a través de info@${BRANDING.appName.toLowerCase().replace(/\s+/g, '')}.com.`,
    },
    en: {
        legalNotice: 'Legal Notice',
        privacyPolicy: 'Privacy Policy',
        cookiesPolicy: 'Cookies Policy',
        termsConditions: 'Terms and Conditions',
        salesConditions: 'Sales Conditions',

        legalNoticeSubtitle: 'Identification and contact details',
        objectTitle: 'Purpose',
        objectDesc: 'The purpose of this website is to provide a digital platform for the management and display of corporate content and services, allowing users to interact directly with the platform.',

        ownerTitle: 'Owner Information',
        ownerName: `${BRANDING.appName} S.L.`,
        ownerFiscalId: 'Tax ID: B-12345678',
        ownerAddress: 'Address: Av. Principal 123, Madrid, Spain',
        ownerEmail: `Contact: info@${BRANDING.appName.toLowerCase().replace(/\s+/g, '')}.com`,

        dataCollection: 'Data Collection',
        dataCollectionDesc: 'We collect personal data necessary for order processing, product shipping, and billing, as well as browsing data to improve experience.',
        dataPurpose: 'Purpose of Treatment',
        dataPurposeDesc: 'Data is used exclusively to process your purchases, manage shipments, handle warranties, and improve our services.',
        userRights: 'User Rights',
        userRightsDesc: `You can exercise your rights of access, rectification, deletion and portability through the integrated support system on the platform or by emailing info@${BRANDING.appName.toLowerCase().replace(/\s+/g, '')}.com.`,
        privacySubtitle: 'How we protect your personal data',

        cookieIntro: 'We use technical cookies necessary for operation and analytical cookies to understand how the site is used.',
        essentialCookies: 'Essential Cookies',
        analyticalCookies: 'Analytical Cookies',
        essentialCookiesDesc: 'Name: `theme-preference`, `language-preference`, `auth-data`. Purpose: Maintain your theme preferences and secure session.',
        analyticalCookiesDesc: 'We use analytics tools to understand usage patterns and improve our online store, without identifying individual users.',
        cookieBannerText: 'We use cookies to ensure the best shopping experience. By continuing, you accept our policy.',
        accept: 'Accept',
        decline: 'Decline',
        moreInfo: 'More info',
        cookiesSubtitle: 'Use of cookies and similar technologies',

        usageRules: 'Usage Rules',
        usageRulesDesc: 'The user agrees to use the platform solely for legitimate inquiries and purchases, avoiding any fraudulent activity.',
        liability: 'Limitation of Liability',
        liabilityDesc: 'Santt Market strives to display accurate information, but we reserve the right to correct errors in prices or descriptions. We are not responsible for technical interruptions beyond our control.',
        intellectualPropertyTitle: 'Intellectual Property',
        intellectualPropertyDesc: 'All content (images, text, software) is the exclusive property of Santt Market S.L. or its licensors. Reproduction without authorization is prohibited.',
        termsSubtitle: 'General conditions of service use',

        salesSubtitle: 'Purchase and returns conditions',
        pricesTitle: '1. Prices and Taxes',
        pricesDesc: 'All prices include applicable VAT. Shipping costs are calculated at checkout before purchase completion.',
        paymentTitle: '2. Payment Methods',
        paymentDesc: 'We accept secure payments via credit/debit card and other methods indicated during the checkout process.',
        withdrawalTitle: '3. Returns and Withdrawal',
        withdrawalDesc: 'You have 14 calendar days to return your order if you are not satisfied, provided products are in their original condition.',
        warrantyTitle: '4. Warranty',
        warrantyDesc: `All our services come with the platform's quality guarantee. For support, contact info@${BRANDING.appName.toLowerCase().replace(/\s+/g, '')}.com.`,
    },
    pt: {
        legalNotice: 'Aviso Legal',
        privacyPolicy: 'Política de Privacidade',
        cookiesPolicy: 'Política de Cookies',
        termsConditions: 'Termos e Condições',
        salesConditions: 'Condições de Contratação',

        legalNoticeSubtitle: 'Identificação e dados de contato',
        objectTitle: 'Objeto',
        objectDesc: 'Este site tem como objetivo a venda online de produtos de tecnologia e eletrônicos, permitindo ao usuário adquirir itens diretamente pela plataforma.',

        ownerTitle: 'Informação do Titular',
        ownerName: `${BRANDING.companyName}`,
        ownerFiscalId: 'NIF: B-12345678',
        ownerAddress: 'Endereço: Av. Principal 123, Madrid, Espanha',
        ownerEmail: `Contato: info@${BRANDING.appName.toLowerCase().replace(/\s+/g, '')}.com`,

        dataCollection: 'Coleta de Dados',
        dataCollectionDesc: 'Coletamos dados pessoais necessários para o processamento de pedidos, envio de produtos e faturação, bem como dados de navegação para melhorar a experiência.',
        dataPurpose: 'Finalidade do Tratamento',
        dataPurposeDesc: 'Os dados são utilizados exclusivamente para processar suas compras, gerenciar envios, atender garantias e melhorar nossos serviços.',
        userRights: 'Direitos do Usuário',
        userRightsDesc: 'Você pode exercer seus direitos de acesso, retificação, exclusão e portabilidade através do sistema de suporte integrado na plataforma ou pelo email legal@santtmarket.com.',
        privacySubtitle: 'Como protegemos seus dados pessoais',

        cookieIntro: 'Utilizamos cookies técnicos necessários para o funcionamento e analíticos para entender como o site é utilizado.',
        essentialCookies: 'Cookies Essenciais',
        analyticalCookies: 'Cookies Analíticos',
        essentialCookiesDesc: 'Nome: `theme-preference`, `language-preference`, `auth-data`. Finalidade: Manter suas preferências de navegação e sessão segura.',
        analyticalCookiesDesc: 'Usamos ferramentas de análise para entender padrões de uso e melhorar nossa plataforma, sem identificar usuários individualmente.',
        cookieBannerText: 'Utilizamos cookies para garantir a melhor experiência. Ao continuar, você aceita nossa política.',
        accept: 'Aceitar',
        decline: 'Recusar',
        moreInfo: 'Mais informações',
        cookiesSubtitle: 'Uso de cookies e tecnologias similares',

        usageRules: 'Regras de Uso',
        usageRulesDesc: 'O usuário compromete-se a utilizar a plataforma apenas para consultas y ações legítimas, evitando qualquer atividade fraudulenta.',
        liability: 'Limitação de Responsabilidade',
        liabilityDesc: `${BRANDING.appName} esforça-se para mostrar informações precisas, mas reservamo-nos o direito de corrigir erros em preços ou descrições. Não nos responsabilizamos por interrupções técnicas fora do nosso controle.`,
        intellectualPropertyTitle: 'Propriedade Intelectual',
        intellectualPropertyDesc: `Todo o conteúdo (imagens, textos, software) é propriedade exclusiva do ${BRANDING.companyName} ou de seus licenciadores. É proibida a reprodução sem autorização.`,
        termsSubtitle: 'Condições gerais de uso do serviço',

        salesSubtitle: 'Condições de serviço e suporte',
        pricesTitle: '1. Preços e Impostos',
        pricesDesc: 'Todos os preços incluem o IVA aplicável se aplicável. Informações detalhadas são fornecidas antes da contratação.',
        paymentTitle: '2. Métodos de Pagamento',
        paymentDesc: 'Aceitamos pagamentos seguros via cartão de crédito/débito e outros métodos indicados no processo de compra.',
        withdrawalTitle: '3. Devoluções e Arrependimento',
        withdrawalDesc: 'Você tem 14 dias corridos para devolver seu pedido se não estiver satisfeito, desde que os produtos estejam em sua condição original.',
        warrantyTitle: '4. Garantia',
        warrantyDesc: `Todos os nossos serviços contam com a garantia de qualidade da plataforma. Para suporte, entre em contato via info@${BRANDING.appName.toLowerCase().replace(/\s+/g, '')}.com.`,
    }
};
