export const traduccionCleanup = {
    es: {
        title: 'Limpieza del Sistema',
        description: 'Elimina datos operativos antiguos para liberar espacio.',
        analyzing: 'Analizando espacio recuperable...',
        metricsEvents: 'Eventos de Métricas',
        activityLogs: 'Registros de Actividad',
        records: 'registros',
        totalReclaimable: 'Total Recuperable',
        warning: 'Esta acción eliminará permanentemente registros con más de {{days}} días de antigüedad. Esto no se puede deshacer.',
        passwordLabel: 'Contraseña de Admin Requerida',
        passwordPlaceholder: 'Ingresa contraseña de admin para confirmar',
        cleaning: 'Limpiando...',
        cleanupSuccess: 'Limpieza Exitosa',
        cleanupSuccessDesc: 'Espacio liberado eliminando registros antiguos.',
        cleanupFailed: 'Limpieza Fallida',
        cleanupFailedDesc: 'Verifica tu contraseña de administrador e intenta nuevamente.',
        metricsUpdate: 'Actualización de Métricas:',
        docsProcessed: 'docs procesados',
        activityLogsDeleted: 'logs eliminados',
        close: 'Cerrar',
        cancel: 'Cancelar',
        confirmCleanup: 'Confirmar Limpieza',
        errorAnalyzing: 'Error al analizar datos de limpieza.',
        errorTitle: 'Error'
    },
    en: {
        title: 'System Cleanup',
        description: 'Remove old operational data to free up space.',
        analyzing: 'Analyzing reclaimable space...',
        metricsEvents: 'Metrics Events',
        activityLogs: 'Activity Logs',
        records: 'records',
        totalReclaimable: 'Total Reclaimable',
        warning: 'This action will permanently delete records older than {{days}} days. This cannot be undone.',
        passwordLabel: 'Admin Password Required',
        passwordPlaceholder: 'Enter admin password to confirm',
        cleaning: 'Cleaning...',
        cleanupSuccess: 'Cleanup Successful',
        cleanupSuccessDesc: 'Freed space by deleting old records.',
        cleanupFailed: 'Cleanup Failed',
        cleanupFailedDesc: 'Verify your admin password and try again.',
        metricsUpdate: 'Metrics Update:',
        docsProcessed: 'docs processed',
        activityLogsDeleted: 'logs deleted',
        close: 'Close',
        cancel: 'Cancel',
        confirmCleanup: 'Confirm Cleanup',
        errorAnalyzing: 'Failed to analyze system cleanup data.',
        errorTitle: 'Error'
    },
    pt: {
        title: 'Limpeza do Sistema',
        description: 'Remova dados operacionais antigos para liberar espaço.',
        analyzing: 'Analisando espaço recuperável...',
        metricsEvents: 'Eventos de Métricas',
        activityLogs: 'Registros de Atividade',
        records: 'registros',
        totalReclaimable: 'Total Recuperável',
        warning: 'Esta ação excluirá permanentemente registros com mais de {{days}} dias. Isso não pode ser desfeito.',
        passwordLabel: 'Senha de Admin Obrigatória',
        passwordPlaceholder: 'Digite a senha de admin para confirmar',
        cleaning: 'Limpando...',
        cleanupSuccess: 'Limpeza Bem-sucedida',
        cleanupSuccessDesc: 'Espaço liberado excluindo registros antigos.',
        cleanupFailed: 'Falha na Limpeza',
        cleanupFailedDesc: 'Verifique sua senha de administrador e tente novamente.',
        metricsUpdate: 'Atualização de Métricas:',
        docsProcessed: 'docs processados',
        activityLogsDeleted: 'logs excluídos',
        close: 'Fechar',
        cancel: 'Cancelar',
        confirmCleanup: 'Confirmar Limpeza',
        errorAnalyzing: 'Falha ao analisar dados de limpeza do sistema.',
        errorTitle: 'Erro'
    }
};
