import type { Language } from '../../../contexts/LanguageContext/context';
import { BRANDING } from '@/config/branding';

export type ITranslation = { [key in Language]: Record<string, string> };

export const traducciones: ITranslation = {
    es: {
        title: "Componentes UI",
        description: `Biblioteca de componentes atómicos de ${BRANDING.appName}. Diseñados para ser rápidos, accesibles y visualmente impactantes.`,
        actions: "Acciones y Herramientas",
        actionsDesc: "Componentes para interacción directa y ayuda visual.",
        forms: "Formularios y Controles",
        formsDesc: "Elementos de entrada de datos y selección.",
        dataDisplay: "Visualización de Datos",
        dataDisplayDesc: "Estructuras para presentar información compleja.",
        feedback: "Retroalimentación y Estados",
        feedbackDesc: "Mensajes de carga, errores y notificaciones.",
        navigation: "Navegación",
        navigationDesc: "Componentes para mover al usuario por la interfaz.",
        backHome: "Volver al Inicio",
        toastHeading: "Notificaciones (Toasts)",
        successTitle: "¡Éxito!",
        successMessage: "La operación se completó correctamente.",
        successTrigger: "Disparar Éxito",
        errorTitle: "Error",
        errorMessage: "Hubo un fallo al procesar la solicitud.",
        errorTrigger: "Disparar Error",
        warningTitle: "Atención",
        warningMessage: "Revisa los datos antes de continuar.",
        warningTrigger: "Disparar Aviso",
        infoTitle: "Información",
        infoMessage: "Hay una nueva actualización disponible.",
        infoTrigger: "Disparar Info",
        stabilityTitle: "Estabilidad (ErrorBoundary)",
        stabilityDesc: "Prueba la resiliencia de la interfaz capturando errores en tiempo de ejecución.",
        stabilityBody: "Haz clic en el botón para lanzar un error. El ErrorBoundary capturará el fallo y mostrará una interfaz de recuperación sin romper el resto de la página.",
        bugTrigger: "Explotar Componente",
        bugError: "¡BOOM! Este es un error de prueba.",
        modalTitle: "Modal de Componente",
        modalBody: "Este es un ejemplo del componente modal funcionando dentro de la página de demostración. Observa las animaciones suaves y el efecto de desenfoque de fondo.",
        close: "Cerrar",
        // New keys
        emailLabel: "Correo Electrónico",
        passwordLabel: "Contraseña",
        messageLabel: "Mensaje",
        acceptTerms: "Aceptar términos",
        overview: "Resumen",
        settings: "Ajustes",
        history: "Historial",
        store: "Tienda",
        price: "Precio",
        savings: "Ahorro",
        action: "Acción",
        showInfo: "Ver Info",
        openModal: "Abrir Modal",
    },
    en: {
        title: "UI Components",
        description: `${BRANDING.appName} atomic component library. Designed to be fast, accessible, and visually stunning.`,
        actions: "Actions and Tools",
        actionsDesc: "Components for direct interaction and visual aid.",
        forms: "Forms and Controls",
        formsDesc: "Data input and selection elements.",
        dataDisplay: "Data Display",
        dataDisplayDesc: "Structures for presenting complex information.",
        feedback: "Feedback and States",
        feedbackDesc: "Loading messages, errors, and notifications.",
        navigation: "Navigation",
        navigationDesc: "Components for moving the user through the interface.",
        backHome: "Back to Home",
        toastHeading: "Notifications (Toasts)",
        successTitle: "Success!",
        successMessage: "The operation completed successfully.",
        successTrigger: "Trigger Success",
        errorTitle: "Error",
        errorMessage: "There was a failure processing the request.",
        errorTrigger: "Trigger Error",
        warningTitle: "Warning",
        warningMessage: "Review the data before continuing.",
        warningTrigger: "Trigger Warning",
        infoTitle: "Info",
        infoMessage: "A new update is available.",
        infoTrigger: "Trigger Info",
        stabilityTitle: "Stability (ErrorBoundary)",
        stabilityDesc: "Test UI resilience by capturing runtime errors.",
        stabilityBody: "Click the button to throw an error. The ErrorBoundary will catch it and show a recovery UI without breaking the page.",
        bugTrigger: "Explode Component",
        bugError: "BOOM! This is a test error.",
        modalTitle: "Component Modal",
        modalBody: "This is an example of the modal component working within the showcase page. Notice the smooth animations and backdrop blur effect.",
        close: "Close",
        // New keys
        emailLabel: "Email Address",
        passwordLabel: "Password",
        messageLabel: "Message",
        acceptTerms: "Accept terms",
        overview: "Overview",
        settings: "Settings",
        history: "History",
        store: "Store",
        price: "Price",
        savings: "Savings",
        action: "Action",
        showInfo: "Show Info",
        openModal: "Open Modal",
    },
    pt: {
        title: "Componentes UI",
        description: `Biblioteca de componentes atômicos do ${BRANDING.appName}. Projetada para ser rápida, acessível e visualmente impactante.`,
        actions: "Ações e Ferramentas",
        actionsDesc: "Componentes para interação direta e auxílio visual.",
        forms: "Formulários e Controles",
        formsDesc: "Elementos de entrada de dados e seleção.",
        dataDisplay: "Visualização de Dados",
        dataDisplayDesc: "Estruturas para apresentar informações complexas.",
        feedback: "Feedback e Estados",
        feedbackDesc: "Mensagens de carregamento, erros e notificações.",
        navigation: "Navegação",
        navigationDesc: "Componentes para mover o usuário pela interface.",
        backHome: "Voltar ao Início",
        toastHeading: "Notificações (Toasts)",
        successTitle: "Sucesso!",
        successMessage: "A operação foi concluída com sucesso.",
        successTrigger: "Disparar Sucesso",
        errorTitle: "Erro",
        errorMessage: "Houve uma falha ao processar a solicitação.",
        errorTrigger: "Disparar Erro",
        warningTitle: "Atenção",
        warningMessage: "Revise os dados antes de continuar.",
        warningTrigger: "Disparar Aviso",
        infoTitle: "Informação",
        infoMessage: "Há uma nova atualização disponível.",
        infoTrigger: "Disparar Info",
        stabilityTitle: "Estabilidade (ErrorBoundary)",
        stabilityDesc: "Teste a resiliência da interface capturando erros em tempo de execução.",
        stabilityBody: "Clique no botão para lançar um erro. O ErrorBoundary irá capturá-lo e mostrar uma interface de recuperação sem quebrar a página.",
        bugTrigger: "Explodir Componente",
        bugError: "BOOM! Este é um erro de teste.",
        modalTitle: "Modal de Componente",
        modalBody: "Este é um exemplo do modal funcionando dentro da página de demonstração. Observe as animações suaves e o efeito de desfoque de fundo.",
        close: "Fechar",
        // New keys
        emailLabel: "Endereço de Email",
        passwordLabel: "Senha",
        messageLabel: "Mensagem",
        acceptTerms: "Aceitar termos",
        overview: "Visão Geral",
        settings: "Configurações",
        history: "Histórico",
        store: "Loja",
        price: "Preço",
        savings: "Economia",
        action: "Ação",
        showInfo: "Ver Info",
        openModal: "Abrir Modal",
    }
};
